title: Leon liu # your name (or website title) here
logo: "/avatar.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  UI/UX/Graphic Designer
  <br><br>
  Contact Me: +86 13810829511   Lfapoc@hotmail.com
  <br><br>
  <a href="https://pan.baidu.com/s/1AhjkKCjWIOrBgCyil1SWvw">Download my portfolio</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
